FROM node:20-alpine

WORKDIR /app
COPY . .

RUN yarn install --frozen-lockfile
RUN yarn tsc

WORKDIR /app/packages/backend
RUN yarn build
RUN yarn install --frozen-lockfile --production

CMD ["node", "dist/index.js"]
