FROM node:20-alpine as builder

WORKDIR /app
COPY . .

RUN yarn install --frozen-lockfile
RUN yarn tsc
RUN yarn build:frontend

FROM nginx:alpine
COPY --from=builder /app/packages/app/dist /usr/share/nginx/html
